#version 450
#extension GL_GOOGLE_include_directive : require
#include "cloud_noise.glsl"
layout(local_size_x=4,local_size_y=4,local_size_z=4) in;
layout(set=1,binding=0,rgba8) uniform writeonly image3D noiseVolume;
void main()
{
    ivec3 p=ivec3(gl_GlobalInvocationID), size=imageSize(noiseVolume);
    if(any(greaterThanEqual(p,size))) return;
    vec2 noise=cloudNoise((vec3(p)+0.5)/vec3(size));
    imageStore(noiseVolume,p,vec4(noise,0.0,0.0));
}
